# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      permalink: 'blog/:title'

permalink:           pretty

# Setup
title:               Dylan Barnard
url:                 http://dylankb.github.io/
paginate:            1
baseurl:             ""

# Structure
pages_list:
  About: '/about/'
  Archive: '/archive/'

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Plugins
gems:               
  - jekyll-paginate 
  - jekyll-gist

# Syntax details
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# About/contact
author:
  name:              Dylan Barnard
  url:               http://dylankb.github.io/

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
