# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Dylan Barnard
url:                 http://dylankb.github.io/
paginate:            1
baseurl:             ""

# Structure
pages_list:
  About: '/about/'
  Archive: '/archive/'


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


# Plugins
gems:               
  - jekyll-paginate 
  - redcarpet
  - jekyll-gist
  - pygments.rb

# About/contact
author:
  name:              Dylan Barnard
  url:               http://dylankb.github.io/
  email:             dylan.barnard@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
